### ISSUE TITLE
app crashes whenever <Link to Dropbox> is solicited

### ISSUE THREAD

**Issue by m2habert** [orgzly-revived/orgzly-android-revived#202] opened 2024-03-22 17:07 UTC
- I have searched for existing issues that may be the same as or related to mine.

Please complete the following information:

    Device: ASUS zenfone max pro M2
    Android Version: 9
    Orgzly Revived Version: 1.8.18 

Hi there.

I've dowloaded the latest apk file from this repo. But I can't make it work as orgzly crashes whenever I try to set the "link to dropbox" button.

I've tried clearing orgzly's cache and data; also tried installing version 1.8.17... to no avail.

Legacy orgzly, on the contrary, has been syncing with no hassles.

**Comment by m2habert** [comment] 2024-03-22 17:59
Following #195 's tip, I'm relying on the dropSync app to establishing phone/local ›‹ dropbox sync. 

(It has the benefit of having auto sync with a nice mismatch control)

**Comment by amberin** [comment] 2024-03-23 09:53
I'm currently looking at the Dropbox client stuff because of #195 and #197. When did you install the legacy Orgzly app? Dropbox stopped handing out long-lived tokens some time ago, and our code needs updating to handle the new workflow. But clearly, you have a different problem than #195. I will try to reproduce on Android 9.

**Comment by m2habert** [comment] 2024-03-24 05:12
> When did you install the legacy Orgzly app?

mmmm, I can't really tell : I've installed orgzly long ago, intending to learn and move my stuff to org mode, but, as usual, delay after postponements after delays resulted in only now I becoming an org user...

I may have installed the legacy orgzly as far as 2022!

**Comment by maikol-solis** [comment] 2024-03-24 21:51
I can confirm that Dropbox isn't working as expected. I installed the legacy app and Dropbox is syncing without problems.

**Comment by amberin** [comment] 2024-03-24 23:00
> I can confirm that Dropbox isn't working as expected. I installed the legacy app and Dropbox is syncing without problems.

Thank you. How did you set the access token that you used in the legacy app? Are you sure it's not short-lived and will stop working after a few hours?

If legacy and Revived handle Dropbox auth differently, it's a real mystery, since the code was last touched in 2019.

In any case, I am working on implementing the new OAuth flow.

**Comment by maikol-solis** [comment] 2024-03-24 23:42
> @maikol-solis Thank you. How did you set the access token that you used in the legacy app? Are you sure it's not short-lived and will stop working after a few hours?

I really don't know. I just installed the old version and put the repository with the path to my org files. If something happens in the next hours, I'll report back.

**Comment by amberin** [comment] 2024-04-01 08:58
I just realized that we build Orgzly Revived without a valid app key, without which linking will never work. I have been using a dummy app in tests. 

I just tried to create the "Orgzly Revived" app in the Dropbox developer console, but the app name is "already taken". If anyone sees this who has created an app themselves using that name, please get in touch with me.

**Comment by amberin** [comment] 2024-04-11 07:15
I didn't fix it properly in the last beta build (1.8.20-beta.1), but it should work in 1.8.20-beta.2.

**Comment by amberin** [comment] 2024-04-28 07:50
I would love to get confirmation from someone who uses Dropbox repos that version 1.8.20 did in fact solve this issue.

**Comment by m2habert** [comment] 2024-05-03 00:13
I've just tried it out, but, after the "allow page", I get the following error card:
 
  "This app has reached its user limit. Contact the app developer and ask them to use the Dropbox API App Console to increase their app's user limit."

**Comment by amberin** [comment] 2024-05-03 05:15
> I've just tried it out, but, after the "allow page", I get the following error card:
> 
> "This app has reached its user limit. Contact the app developer and ask them to use the Dropbox API App Console to increase their app's user limit."

@m2habert Thanks a million, I wasn't aware of that setting, but I have increased the limit now. If you could try again, that would be great.

**Comment by m2habert** [comment] 2024-05-08 05:09
I confirm that it's woring: I've just linked with the dropbox storage.

Only caveat: I inserted `/org` and orgzly created under `/apps` its depository : `/apps/Orgzly Revived/org` ...

While  I'd rather have `~/Dropbox/org` , like I was using before. ¿Maybe is it a new security thing from drobox?

Thanks!

**Comment by amberin** [comment] 2024-05-08 06:29
@m2habert Thank you very much!

Yes, the app now has a "scoped storage permission", meaning it can only access its own folder. It seemed pretty hard to obtain broader permissions.

Thank you for pointing that out - I didn't notice it in my tests, but it was the same there.

Let's hope it doesn't completely ruin anyone's life.

**Comment by amberin** [comment] 2024-05-08 22:32
This particular issue has been resolved, so I'm closing this.

**Closed** 2024-05-08 22:32 UTC
Labels: bug
