### ISSUE TITLE
Git: Notebooks in subfolders get written to the root folder

### ISSUE THREAD

**Issue by TheEccentricConnisure** [orgzly-revived/orgzly-android-revived#146] opened 2024-01-26 16:31 UTC
I am able to clone my repo properly, but the cloned repo cannot be viewed by the app
![Screenshot_2024-01-24-08-25-41-61_ed2cde8a5c8dee394aae50c5114b3a51](https://github.com/orgzly-revived/orgzly-android-revived/assets/70190820/300ab732-0365-4add-9d3c-68bfa5515a67)

But if I use the normal way like accessing via the mentioned directory (the same one with the cloned repo) I am able to access the notes. And I want to mention that I have two files (directory) in my repo, one for my templates and one with my notes, is this causing the issue. 

I have the following files in the repo: 
1. Alexandria [with my notes and the gtd file]
2. template [folder with all my templates]
3. .gitignore

**Comment by amberin** [comment] 2024-02-02 13:22
I've tried to reproduce this behavior but I failed. Could there be something in your specific filenames which is causing the issue?

Here's what I did:

1. Created a Git repo with the following files:
  ```[orgzlydevuser@t6g repo]$ tree
  .
  ├── Alexandria
  │   ├── one.org
  │   ├── three.org
  │   └── two.org
  └── template
      ├── file1
      ├── notanorgfile.txt
      └── something.json
    
    3 directories, 6 files
```
2. Deleted all local notebooks in Orgzly.
3. Added the new repo in Orgzly.
4. Synced.

The three files one.org, two.org and three.org all show up as expected, without any errors.

![2024-02-02-14-19-34](https://github.com/orgzly-revived/orgzly-android-revived/assets/15090460/20c68ade-3544-4ae3-ab51-9c53bbafa86a)

**Comment by amberin** [comment] 2024-02-02 21:08
While working with the Git repo code for other reasons, and using this repo for testing, I've noticed that the Git repo logic does not handle files in folders well at all. Or rather, the general logic for loading books from a repo does not support the Git use case properly. This is probably what's causing your issues, @TheEccentricConnisure.

**Comment by TheEccentricConnisure** [comment] 2024-02-04 19:17
I see I guess for now I will use syncthing for synchronisation

**Comment by amberin** [comment] 2024-02-04 19:20
You do that, and we'll keep this issue open. It should not be too hard to solve.

**Comment by amberin** [comment] 2024-02-13 11:19
I will fix this and also look at adding some Git repo regression tests.

**Comment by amberin** [comment] 2024-02-13 17:55
I just did some testing with the directory repo type and realized that notebooks in subfolders are not seen at all. Which is better than the Git repo, which writes them into the root directory, but still... Not ideal. 😀

**Comment by stfl** [comment] 2024-02-20 23:06
+1 for namespacing org files in subdirectory.

**Comment by stfl** [comment] 2024-02-20 23:15
aren't the names not taken from the #+title: XYZ property?
my inbox.org has the title `_Inbox` to force it being sorted on top.

**Comment by amberin** [comment] 2024-02-21 22:50
@stfl You are right! I had no idea that was parsed, that's great. That means you can tweak notebook titles as required.

**Comment by stfl** [comment] 2024-03-04 16:21
Are there any issue to fix this? After the .orgzlyignore topic, this is the last remaining issue from adopting orgzly-revived.
I would like to avoid migrating all of my /gtd/*.org files to /*.org.
An alternative could be to clone the repo and adding the required directories separatly like with old orgzly repos.

**Comment by amberin** [comment] 2024-03-04 16:51
Yes, I am currently working on this. I just need to do quite some manual testing to make sure I don't break any repo types, because it requires changes in repo-agnostic code.

I have yet to test with webdav repos, but otherwise it's going well.

I am a little bit concerned that users who have gotten used to the current behavior might react negatively when org files in subfolders which were previously ignored suddenly appear in Orgzly. But we'll see.

**Comment by stfl** [comment] 2024-03-04 17:57
Thanks for clarifying. I agree. Maybe recursive dirs should be a repo-option?

**Comment by amberin** [comment] 2024-03-04 18:11
That's a very good idea. At least for the repo types which currently ignores subfolders. (Git repos are just broken, since they import notebooks in subfolders but can't update them. So there is no risk of unexpected behavior there. And they already have the .orgzlyignore solution.)

A challenge with adding a "recursive" repo option is that directory repos currently don't have any preferences at all, just a DB entry with URL info. So adding repo preferences to them is quite some work.

Another alternative might be to add support for the .orgzlyignore file for all repos along with this change, so users have an easy way of excluding anything they need.

**Comment by stfl** [comment] 2024-03-04 19:06
You might be able to add it as an URL option. Construct the URL in the gui and parse it in the backend?

**Comment by amberin** [comment] 2024-03-07 19:27
That's a very good idea. At least for the repo types which currently ignores subfolders. (Git repos are just broken, since they import notebooks in subfolders but can't update them. So there is no risk of unexpected behavior there. And they already have the .orgzlyignore solution.)

A challenge with adding a "recursive" repo option is that directory repos currently don't have any preferences at all, just a DB entry with URL info. So adding repo preferences to them is quite some work.

Another alternative might be to add support for the .orgzlyignore file for all repos along with this change, so users have an easy way of excluding anything they need.

> You might be able to add it as an URL option. Construct the URL in the gui and parse it in the backend?

That's a neat idea. It could probably be useful for many things. But it feels like a pretty big design choice, since I suppose we would not want some repos to rely on "rich" URLs while others rely on shared prefs. Or maybe that's fine? Not sure.

**Comment by stfl** [comment] 2024-03-08 08:38
In general, I agree that the repo API should be similar and not options as prefs in Dir repos and options as url in the other.

I think it's more important to fix writing files to the correct sub-dir location and .orgzlyignore will be able to handle the rest for now.

**Comment by amberin** [comment] 2024-04-20 08:07
I have now created #224.

**Comment by pjones** [comment] 2024-08-05 21:02
This bit me too.  I just wanted to add my name to the list just in case there's any way I can help with this.

In the meantime I've switch to using syncthing to sync just the directory that contains agenda files.  The nice thing about this solution is that it's really fast compared to using Git.

Thank you for working on Orgzly!

**Comment by amberin** [comment] 2024-08-06 05:22
Subfolder support in all repos is almost finished. I'm working on unit tests right now, then I will open a PR.

**Comment by amberin** [comment] 2024-08-29 13:57
Closing as the real issue is #312 (which will hopefully soon be closed).

**Closed by amberin** 2024-08-29 13:57 UTC
Labels: bug, Git repos
