### ISSUE TITLE
Sub folder support.

### ISSUE THREAD

**Issue by VasilKotsov** [orgzly-revived/orgzly-android-revived#303] opened 2024-08-07 20:55 UTC
Can you add sub folder support in addition to main folder the idea is to sync notes in sub folders. And also add folder layout in notebooks if it possible. Thank you.

**Comment by amberin** [comment] 2024-08-07 22:45
I'm happy to say that this is a duplicate of #175, and that we are very near releasing it. Probably within a month or two.

**Comment by amberin** [comment] 2024-08-09 16:18
Duplicate of #175

**Closed by amberin** 2024-08-09 16:18 UTC
Labels: enhancement
